### ISSUE TITLE
Another awful candidate

### ISSUE THREAD

**Issue by mslinn** [soffes/awfulrecruiters.com#51]
panzersolutions.com

**Comment by jaredwilli** [comment]
Also add:

*@rht.com
*@bowdoingroup.com

**Comment by jaredwilli** [comment]
*@onwardgroup.com

**Comment by nathansmith** [comment]
Added here…

https://github.com/soffes/awfulrecruiters.com/commit/35c755ba84fd16183eeaeb7c7fd5293671791bc4

**Comment by nathansmith** [comment]
Oops, and here…

https://github.com/soffes/awfulrecruiters.com/commit/73d27adfb8a5d145f93edf98c20ff3783c74f06b
